#!/bin/bash

#### 作成ユーザー存在チェック ###########################################################

function UserCheck() {
	if grep "$1" "/etc/passwd" >/dev/null; then

		echo "$1というユーザー名は既に存在します"
		return 1
	else

		return 0

	fi
}

#### ユーザー作成関数 ###################################################################

function Useradd() {
	# ユーザー作成
	adduser "$1" >/dev/null

	if [ "$?" =! 0 ]; then
		
		echo "アカウントの作成が失敗しています！！"
		
		return 1
	fi
}

#### 秘密鍵の作成用関数 #################################################################

function Secret-key-Generate() {
	
}

